//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPackWS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrecePlus2Entities : DbContext
    {
        public CrecePlus2Entities()
            : base("name=CrecePlus2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GuiaPaqueteria> GuiaPaqueteria { get; set; }
        public virtual DbSet<Orden> Orden { get; set; }
        public virtual DbSet<PaqueteEnvio> PaqueteEnvio { get; set; }
        public virtual DbSet<Paqueteria> Paqueteria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
    }
}
