//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPackWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public string numero_orden { get; set; }
        public string id_cliente { get; set; }
        public string calle { get; set; }
        public string codigo_postal { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
        public string tipo_envio { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
