//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPackWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaqueteEnvio
    {
        public byte[] detalle_impresion { get; set; }
        public string numero_orden { get; set; }
        public string numero_guia { get; set; }
        public string folio_recoleccion { get; set; }
    
        public virtual GuiaPaqueteria GuiaPaqueteria { get; set; }
    }
}
